OENIK_PROG3_2020_2_FTX89J/FootballDatabase.Web/Models/Player.cs
// <copyright file="Player.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FootballDatabase.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Model class representing a football player.
    /// </summary>
    public class Player
    {
        /// <summary>
        /// Gets or sets the id of a player.
        /// </summary>
        [Display(Name="Player Id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the player's name.
        /// </summary>
        [Display(Name = "Player Name")]
        [Required]
        [MaxLength(60)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the player's birthday.
        /// </summary>
        [Display(Name = "Player Birthday")]
        [Required]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets the player's position.
        /// </summary>
        [Display(Name = "Player Position")]
        [Required]
        public string Position { get; set; }

        /// <summary>
        /// Gets or sets the number on the player's shirt.
        /// </summary>
        [Display(Name = "Player Number")]
        [Required]
        public int Number { get; set; }

        /// <summary>
        /// Gets or sets how many goals the player has scored in the current season.
        /// </summary>
        [Display(Name = "Player Goals")]
        [Required]
        public int Goals { get; set; }

        /// <summary>
        /// Gets or sets how many assists the player has given in the current season.
        /// </summary>
        [Display(Name = "Player Assists")]
        [Required]
        public int Assists { get; set; }

        /// <summary>
        /// Gets or sets how many matches the player has played in the current season.
        /// </summary>
        [Display(Name = "Player Matches")]
        [Required]
        public int Matches { get; set; }

        /// <summary>
        /// Gets or sets the player's nationality.
        /// </summary>
        [Display(Name = "Player Nationality")]
        [Required]
        public string Nationality { get; set; }

        /// <summary>
        /// Gets or sets the player's current market value in euros.
        /// </summary>
        [Display(Name = "Player Marketvalue")]
        public int MarketValue { get; set; }

        /// <summary>
        /// Gets or sets which team the player is playing in.
        /// </summary>
        [Display(Name = "Player Team")]
        public string Team { get; set; }
    }
}

OENIK_PROG3_2020_2_FTX89J/FootballDatabase.Web/Controllers/PlayersController.cs
// <copyright file="PlayersController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FootballDatabase.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using FootballDatabase.Logic;
    using FootballDatabase.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Player controller class.
    /// </summary>
    public class PlayersController : Controller
    {
        private IStatisticalLogic statisticalLogic;
        private ITransferLogic transferLogic;
        private IFinancialLogic financialLogic;
        private IMapper mapper;
        private PlayerListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="PlayersController"/> class.
        /// </summary>
        /// <param name="statisticalLogic">IStatisticalLogic DI.</param>
        /// <param name="transferLogic">ITransferLogic DI.</param>
        /// <param name="financialLogic">IFinancialLogic DI.</param>
        /// <param name="mapper">IMapper DI.</param>
        public PlayersController(IStatisticalLogic statisticalLogic, ITransferLogic transferLogic, IFinancialLogic financialLogic, IMapper mapper)
        {
            this.statisticalLogic = statisticalLogic;
            this.transferLogic = transferLogic;
            this.financialLogic = financialLogic;
            this.mapper = mapper;

            this.vm = new PlayerListViewModel();
            this.vm.EditedPlayer = new Models.Player();

            var players = this.statisticalLogic.GetAllPlayers();
            this.vm.ListOfPlayers = this.mapper.Map<IList<Data.Player>, List<Models.Player>>(players);
        }

        /// <summary>
        /// Method for sendig a response of the Index page.
        /// </summary>
        /// <returns>An IAction result.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("PlayersIndex", this.vm);
        }

        /// <summary>
        /// Method for getting a player with a certain id.
        /// </summary>
        /// <param name="id">Id of the player.</param>
        /// <returns>IAction result.</returns>
        public IActionResult Details(int id)
        {
            return this.View("PlayersDetails", this.GetPlayer(id));
        }

        /// <summary>
        /// Method for removing a player with a certain Ii.
        /// </summary>
        /// <param name="id">The id of the player.</param>
        /// <returns>IAction result.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete failed.";
            if (this.transferLogic.RemovePlayer(this.statisticalLogic.GetOnePlayer(id)))
            {
                this.TempData["editResult"] = "Delete successful.";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Method for editing a player.
        /// </summary>
        /// <param name="id">The player's id.</param>
        /// <returns>IAction result.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedPlayer = this.GetPlayer(id);
            return this.View("PlayersIndex", this.vm);
        }

        /// <summary>
        /// Method for editing a player.
        /// </summary>
        /// <param name="player">The edited Player object.</param>
        /// <param name="editAction">Status of edit.</param>
        /// <returns>IAction result.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Player player, string editAction)
        {
            if (this.ModelState.IsValid && player != null)
            {
                int teamId = this.statisticalLogic.GetIdFromTeamName(player.Team);
                this.TempData["editResult"] = "Edit successful.";
                if (editAction == "AddNew")
                {
                    if (teamId != 0)
                    {
                        this.transferLogic.InsertPlayer(new Data.Player()
                        {
                            Assists = player.Assists,
                            DateOfBirth = player.DateOfBirth,
                            Goals = player.Goals,
                            MarketValue = player.MarketValue,
                            Matches = player.Matches,
                            Name = player.Name,
                            Nationality = player.Nationality,
                            Number = player.Number,
                            Position = player.Position,
                            TeamId = teamId,

                            // Team = this.statisticalLogic.GetOneTeam(teamId),
                        });
                    }
                    else
                    {
                        this.TempData["editResult"] = "Insertion failed. Team doesn't exist.";
                    }
                }
                else
                {
                    if (teamId != 0)
                    {
                        this.statisticalLogic.ChangePlayerName(player.Id, player.Name);
                        this.statisticalLogic.ChangePlayerGoals(player.Id, player.Goals);
                        this.statisticalLogic.ChangePlayerMatches(player.Id, player.Goals);
                        this.statisticalLogic.ChangePlayerAssists(player.Id, player.Assists);
                        this.statisticalLogic.ChangePlayerBirthday(player.Id, player.DateOfBirth);
                        this.statisticalLogic.ChangePlayerNationality(player.Id, player.Nationality);
                        this.statisticalLogic.ChangePlayerPosition(player.Id, player.Position);
                        this.statisticalLogic.ChangePlayerNumber(player.Number, player.Number);
                        this.transferLogic.ChangePlayerTeamId(player.Id, teamId);
                        this.financialLogic.ChangePlayerMarketValue(player.Id, player.MarketValue);
                    }
                    else
                    {
                        this.TempData["editResult"] = "Edit failed. Team doesn't exist.";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedPlayer = player;
                return this.View("PlayersIndex", this.vm);
            }
        }

        private Models.Player GetPlayer(int id)
        {
            Data.Player onePlayer = this.statisticalLogic.GetOnePlayer(id);
            return this.mapper.Map<Data.Player, Models.Player>(onePlayer);
        }
    }
}

OENIK_PROG3_2020_2_FTX89J/FootballDatabase.Web/Views/Players/PlayersDetails.cshtml
@model FootballDatabase.Web.Models.Player

@{
    ViewData["Title"] = "PlayersDetails";
}

<h2>Player infos</h2>

@Html.ActionLink("Back to list of players", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(model => model.Id)</td>
        <td>@Html.DisplayFor(model => model.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Name)</td>
        <td>@Html.DisplayFor(model => model.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.DateOfBirth)</td>
        <td>@Html.DisplayFor(model => model.DateOfBirth)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Team)</td>
        <td>@Html.DisplayFor(model => model.Team)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Nationality)</td>
        <td>@Html.DisplayFor(model => model.Nationality)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Number)</td>
        <td>@Html.DisplayFor(model => model.Number)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Position)</td>
        <td>@Html.DisplayFor(model => model.Position)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Matches)</td>
        <td>@Html.DisplayFor(model => model.Matches)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Goals)</td>
        <td>@Html.DisplayFor(model => model.Goals)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Assists)</td>
        <td>@Html.DisplayFor(model => model.Assists)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.MarketValue)</td>
        <td>@Html.DisplayFor(model => model.MarketValue)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_FTX89J/FootballDatabase.Web/Views/Players/PlayersEdit.cshtml
@model FootballDatabase.Web.Models.Player

<h2>Player Editor</h2>

@using (Html.BeginForm("Edit", "Players"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.Id)

    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(model => model.Name)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Name)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Team)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Team)</div>

    <div class="editor-label">@Html.LabelFor(model => model.DateOfBirth)</div>
    <div class="editor-field">@Html.EditorFor(model => model.DateOfBirth)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Nationality)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Nationality)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Number)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Number)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Position)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Position)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Matches)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Matches)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Goals)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Goals)</div>

    <div class="editor-label">@Html.LabelFor(model => model.Assists)</div>
    <div class="editor-field">@Html.EditorFor(model => model.Assists)</div>

    <div class="editor-label">@Html.LabelFor(model => model.MarketValue)</div>
    <div class="editor-field">@Html.EditorFor(model => model.MarketValue)</div>

    <input type="submit" value="Edit" />
}

OENIK_PROG3_2020_2_FTX89J/FootballDatabase.Web/Views/Players/PlayersIndex.cshtml
@model FootballDatabase.Web.Models.PlayerListViewModel

@{
    ViewData["Title"] = "PlayersIndex";
}

<h2>Players Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("PlayersEdit", Model.EditedPlayer)

@await Html.PartialAsync("PlayersList", Model.ListOfPlayers)

OENIK_PROG3_2020_2_FTX89J/FootballDatabase.Web/Views/Players/PlayersList.cshtml
@model IEnumerable<FootballDatabase.Web.Models.Player>

<h2>List of Players</h2>

@if (Model.Count() == 0) 
{ 
    <p>There is no players in the database.</p>
}
else 
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(model => model.First().Name)</th>
        <th>@Html.DisplayNameFor(model => model.First().Team)</th>
        <th>Player Info</th>
        <th>Delete</th>
        <th>Modifiy</th>
    </tr>
    @foreach (var player in Model)
    {
        <tr>
            <td>@Html.DisplayFor(model => player.Name)</td>
            <td>@Html.DisplayFor(model => player.Team)</td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { id = player.Id })</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = player.Id })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { id = player.Id })</td>
        </tr>
    }
</table>
}